# version: '3.9'

services:

  nginx:
    # image: nginx #:1.19.8-alpine
    build: .
    image: nginx_auth:stable
    container_name: nginx
    ports:
      - "8080:80"
      - "2443:443"
      # volumes:
      #   - ./nginx-conf.d:/etc/nginx/conf.d
      # - .htpasswd:/etc/nginx/.htpasswd
